// This test automatically generated by doctor-general.
// Sourced from 'interpreter.js', edits to this file may be erased.
import { arity } from '../interpreter'

test('arity', () => {
  expect(arity((a, b, c) => {})).toEqual(3)
  expect(arity(function tertiary(a, b, c) {})).toEqual(3)
  expect(arity(a => b => c => c)).toEqual(1)
  expect(arity('poo')).toEqual(-1)
})
