// This test automatically generated by doctor-general.
// Sourced from 'parse.js', edits to this file may be erased.
import { parse } from '../parse'

import { MAGIC_COMMENT_END, MAGIC_COMMENT_START } from '../parse'
test('parse,exampleFunction', () => {
  const RAW = `
  This is my really cool function
  @name exampleFunction
  `
  const pseudocomment = z =>
    [
      MAGIC_COMMENT_START,
      z
        .split('\n')
        .map(y => '* ' + y)
        .join('\n'),
      MAGIC_COMMENT_END,
    ].join('')
  const FILENAME = 'monoculture/packages/cool/myfile.js'
  const parsed = parse(FILENAME, pseudocomment(RAW))
  expect(parsed).toEqual({
    comments: [
      {
        addTo: '',
        end: 3,
        fileGroup: '',
        keywords: ['@name'],
        lines: RAW.split('\n').filter(z => z.trim()),
        links: [],
        start: 0,
        structure: {},
        summary: RAW,
      },
    ],
    fileGroup: undefined,
    filename: FILENAME,
    links: [],
    order: 0,
    package: 'cool',
    pageSummary: '',
    pageTitle: undefined,
    slugName: 'myfile',
  })
})
