// This test automatically generated by doctor-general.
// Sourced from 'reader.js', edits to this file may be erased.
import { iterateOverWorkspacesAndReadFiles } from '../reader'

import { fork, resolve as resolveF } from 'fluture'
test('iterateOverWorkspacesAndReadFiles', done => {
  fork(done)(x => {
    expect(x).toEqual([
      'tools/digested',
      'tools/doctor-general-cli',
      'tools/gitparty',
      'tools/spacework',
      'tools/superorganism',
      'tools/treacle',
    ])
    done()
  })(
    iterateOverWorkspacesAndReadFiles(
      {
        searchGlob: '*',
        ignore: [],
      },
      '../..',
      resolveF(['tools/'])
    )
  )
})
