// This test automatically generated by doctor-general.
// Sourced from 'reader.js', edits to this file may be erased.
import {
  iterateOverWorkspacesAndReadFiles
} from '../reader'

import { fork, resolve, parallel } from 'fluture'
test('iterateOverWorkspacesAndReadFiles', (done) => {
  fork(done)(x => {
    expect(x).toEqual([])
    done()
  })(
    parallel(10)(
      iterateOverWorkspacesAndReadFiles(
        {
          searchGlob: '*',
          ignore: []
        },
        '..',
        resolve(['tools/'])
      )
    )
  )
})
