plugins = [
  "./plugin-c-words.js",
  "./plugin-has-exports.js",
  "./plugin-get-imports.js",
  "./plugin-wordcount.js",
  "./plugin-get-exports.js",
  "../../robot-tourist/monocle-plugin-simple.js",
  "../../robot-tourist/monocle-plugin-main.js",
  "./plugin-has-imports.js",
]
ignore = [
  "**/__snapshots__/*",
  "**/coverage/**/*",
  "*.svg",
  "**/monocle-findings.json"
]

[robot-tourist]
dropStrings = true

