plugins = [
  "../../robot-tourist/dist/monocle-plugin-main.cjs",
  "./plugin-get-imports.js",
  "./plugin-c-words.js",
  "./plugin-has-exports.js",
  "./plugin-get-exports.js",
  "../../robot-tourist/dist/monocle-plugin-simple.cjs",
  "./plugin-has-imports.js",
  "./plugin-wordcount.js",
]
ignore = [
  "./**/__snapshots__/*",
  "./**/coverage/**/*",
  "./**/*.svg",
  "./**/monocle-findings.json",
  "./**/ci-report.json"
]

[robot-tourist]
dropStrings = true

