// This test automatically generated by doctor-general.
// Sourced from 'primitives.js', edits to this file may be erased.
import { equalishBy, coerce } from '../primitives'

test('equalishBy', () => {
  const productIdSelector = z => {
    const d = z.indexOf('-')
    return d > -1 ? z.slice(0, d) : 'NO_MATCH'
  }
  const isProduct = equalishBy(productIdSelector, 'coolco')

  expect(isProduct('coolco-10020')).toBeTruthy()
  expect(isProduct('otherco-xkswn')).toBeFalsy()
  expect(isProduct('blabbo')).toBeFalsy()
})

test('coerce', () => {
  expect(coerce(0)).toBeFalsy()
  expect(coerce('')).toBeFalsy()
  expect(coerce([])).toBeTruthy()
  expect(coerce(1)).toBeTruthy()
})
