// This test automatically generated by doctor-general.
// Sourced from 'cabal.js', edits to this file may be erased.
import {
  hasOrAdd
} from '../cabal'

test('hasOrAdd', () => {
  const s = new Set()
  const key = Math.floor(Math.random() * 1e3)
  s.add(key)
  const hooked = hasOrAdd(s)
  expect(hooked(key)).toBeTruthy()
  expect(hooked('nice')).toBeFalsy()
})
