import { makeRegexFromArray } from './regex'
export const TS_KEYWORDS = [
  'any',
  'boolean',
  'string',
  'number',
  'interface',
  'type',
]
export const JS_KEYWORDS = [
  'Error',
  'switch',
  'case',
  'class',
  'as',
  'async',
  'await',
  'catch',
  'children',
  'const',
  'default',
  'else',
  'export',
  'for',
  'forEach',
  'from',
  'function',
  'if',
  'import',
  'length',
  'let',
  'map',
  'null',
  'push',
  'reduce',
  'return',
  'then',
  'this',
  'try',
  'undefined',
  'var',
  'while',
  'extends',
  'new',
]
export const RG_JS_KEYWORDS = makeRegexFromArray(JS_KEYWORDS)
export const RG_TS_KEYWORDS = makeRegexFromArray(TS_KEYWORDS)
export const SOURCE_CODE_NOISE = /[\+\$\!\|;:\.%\[\]<>,\=\)\(\}\{&\?\d]/gs
