// package-scripts.cjs generated by plopfile
const sd = (script, description = '') =>
  !!description ? { script, description } : { script }
const build = ([infile, outfile]) =>
  [
    // `NODE_PATH="./node_modules:../../node_modules"`,
    `esbuild`,
    `${infile}`,
    `--outfile=${outfile}`,
    `--bundle`,
    `--format=esm`,
    `--platform=node`,
    `--packages=external`,
    `--banner:js="#!/usr/bin/env node"`,
  ].join(' ')
const INPUT = `src/index.js`
const OUTPUT = `fl-utils.js`
module.exports = {
  scripts: {
    build: {
      ...sd(build([INPUT, OUTPUT]), 'build!'),
    },
    lint: sd('eslint --fix .', 'lint!'),
    test: {
      ...sd(
        'jest --testPathIgnorePatterns ".*" --passWithNoTests',
        'skip running tests in CI'
      ),
      all: sd('jest', 'test'),
      watch: sd('jest --watch', 'test with watch-mode!'),
    },
    meta: {
      graph: `madge ${INPUT} --image graph.svg`,
    },
  },
}
