module.exports = {
  root: true,
  env: {
    node: true,
    es6: true,
    jest: true,
  },
  parserOptions: {
    ecmaVersion: 7,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  parser: '@typescript-eslint/parser',
  rules: {
    'no-console': 2,
    camelcase: 2,
    'no-dupe-keys': 1,
    // this was done to avoid enums matching in TS?
    'no-undef': 2,
    'no-new': 2,
    'one-var': 0,
    'dot-notation': 2,
    'prefer-promise-reject-errors': 2,
    'spaced-comment': 2,
    'lines-between-class-members': 2,
    'prefer-const': 2,
    'prettier/prettier': 2,
    'no-extra-semi': 2,
    'no-extra-boolean-cast': 0,
    'no-var': 2,
    eqeqeq: [2, 'smart'],
    'arrow-parens': [2, 'as-needed'],
    'consistent-this': 2,
    'func-names': [2],
    'max-len': [2, 100, 2],
    'new-cap': [2, { capIsNew: false }],
    'no-trailing-spaces': [2, { skipBlankLines: true }],
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': [
      1,
      { varsIgnorePattern: '^_', argsIgnorePattern: '^_' },
    ],
    'no-unused-expressions': 2,
    'no-sequences': 2,
    'no-return-assign': 2,
    'no-void': 2,
    'no-constant-condition': 2,
    'no-restricted-globals': 2,
    'import/no-absolute-path': 2,
    'no-shadow': 0,
    '@typescript-eslint/no-shadow': [
      2,
      { builtinGlobals: false, hoist: 'all' },
    ],
    'no-unneeded-ternary': 2,
    'no-proto': 2,
    'no-useless-return': 2,
    'import/no-named-default': 2,
    'import/named': 0,
    'no-redeclare': 0,
    'import/no-mutable-exports': 2,
    'import/order': 0,
    'import/no-duplicates': 2,
    'import/extensions': [
      2,
      {
        json: 'always',
        dumb: 'always',
        js: 'never',
      },
    ],
    'react-hooks/rules-of-hooks': 2,
    'react/jsx-key': 2,
    'object-shorthand': 2,
    // jsdoc
    // we are using jsdoc in concert with daffy-doc and typescript, so we can turn some rules off
    'jsdoc/check-tag-names': 0,
    'jsdoc/require-jsdoc': 0,
    'jsdoc/require-returns': 0,
    'jsdoc/require-returns-check': 0,
    'jsdoc/require-returns-description': 0,
    'jsdoc/require-returns-type': 0,
    'jsdoc/require-param': 0,
    'jsdoc/require-param-description': 0,
    'jsdoc/require-param-name': 0,
    'jsdoc/require-param-type': 0,
    'jsdoc/require-example': 2,
    'jsdoc/no-undefined-types': 0,
  },
  // extends: ["standard", "prettier", "next/core-web-vitals"],
  extends: ['next', 'turbo', 'prettier', 'plugin:jsdoc/recommended-typescript'],
  plugins: [
    'babel',
    'fp',
    'import',
    'prettier',
    'ramda',
    '@typescript-eslint',
    'jsdoc',
  ],
}
