import { fork } from 'fluture'
import {
  dotStreamAdapterWithCancel,
  setAttribute,
  setColor,
  getCyclic,
  createGraph,
  generateOptions,
  createSVG,
} from './visualization'
import { checkForBinaries } from './executables'
import { DEFAULT_GRAPHVIZ_CONFIG } from './constants'

test('dotStreamAdapterWithCancel', () => {
  expect(dotStreamAdapterWithCancel).toBeTruthy()
})
test('setAttribute', () => {
  expect(setAttribute).toBeTruthy()
})
test('setColor', () => {
  expect(setColor).toBeTruthy()
})
test('getCyclic', () => {
  expect(getCyclic).toBeTruthy()
})
test('createGraph', () => {
  expect(createGraph).toBeTruthy()
})
test('generateOptions', () => {
  expect(generateOptions).toBeTruthy()
  expect(generateOptions({})).toMatchSnapshot()
})
test('createSVG', done => {
  const cancel = () => {}
  expect(createSVG).toBeTruthy()
  fork(() => {
    // eslint-disable-next-line no-console
    console.log('SKIPPING GVPR TESTS')
    expect('skipping tests which rely upon `gvpr`').toBeTruthy()
    done()
  })(raw => {
    // eslint-disable-next-line no-console
    console.log('RUNNING GVPR TESTS', raw)
    const modules = { 'a.js': ['b.js', 'c.js'], 'b.js': ['c.js'], 'c.js': [] }
    fork(done)(z => {
      /* eslint-disable max-len */
      expect(z.toString()).toMatchInlineSnapshot(`
"<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 9.0.0 (20230911.1827)
 -->
<!-- Title: G Pages: 1 -->
<svg width="280pt" height="95pt"
 viewBox="0.00 0.00 280.20 94.95" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(21.6 73.35)">
<title>G</title>
<polygon fill="#111111" stroke="none" points="-21.6,21.6 -21.6,-73.35 258.6,-73.35 258.6,21.6 -21.6,21.6"/>
<!-- a.js -->
<g id="node1" class="node">
<title>a.js</title>
<path fill="none" stroke="#ffffff" d="M45.08,-29.75C45.08,-29.75 9.92,-29.75 9.92,-29.75 4.96,-29.75 0,-24.79 0,-19.83 0,-19.83 0,-9.92 0,-9.92 0,-4.96 4.96,0 9.92,0 9.92,0 45.08,0 45.08,0 50.04,0 55,-4.96 55,-9.92 55,-9.92 55,-19.83 55,-19.83 55,-24.79 50.04,-29.75 45.08,-29.75"/>
<text text-anchor="middle" x="27.5" y="-10.55" font-family="Fira Code" font-size="16.00" fill="#ffffff">a.js</text>
</g>
<!-- b.js -->
<g id="node2" class="node">
<title>b.js</title>
<path fill="none" stroke="#ffffff" d="M136.08,-51.75C136.08,-51.75 100.92,-51.75 100.92,-51.75 95.96,-51.75 91,-46.79 91,-41.83 91,-41.83 91,-31.92 91,-31.92 91,-26.96 95.96,-22 100.92,-22 100.92,-22 136.08,-22 136.08,-22 141.04,-22 146,-26.96 146,-31.92 146,-31.92 146,-41.83 146,-41.83 146,-46.79 141.04,-51.75 136.08,-51.75"/>
<text text-anchor="middle" x="118.5" y="-32.55" font-family="Fira Code" font-size="16.00" fill="#ffffff">b.js</text>
</g>
<!-- a.js&#45;&gt;b.js -->
<g id="edge1" class="edge">
<title>a.js&#45;&gt;b.js</title>
<path fill="none" stroke="#888888" d="M55.2,-21.48C62.88,-23.37 71.4,-25.48 79.61,-27.51"/>
<polygon fill="#888888" stroke="#888888" points="78.49,-30.84 89.04,-29.84 80.17,-24.04 78.49,-30.84"/>
</g>
<!-- c.js -->
<g id="node3" class="node">
<title>c.js</title>
<path fill="none" stroke="#00cc00" d="M227.08,-29.75C227.08,-29.75 191.92,-29.75 191.92,-29.75 186.96,-29.75 182,-24.79 182,-19.83 182,-19.83 182,-9.92 182,-9.92 182,-4.96 186.96,0 191.92,0 191.92,0 227.08,0 227.08,0 232.04,0 237,-4.96 237,-9.92 237,-9.92 237,-19.83 237,-19.83 237,-24.79 232.04,-29.75 227.08,-29.75"/>
<text text-anchor="middle" x="209.5" y="-10.55" font-family="Fira Code" font-size="16.00" fill="#ffffff">c.js</text>
</g>
<!-- a.js&#45;&gt;c.js -->
<g id="edge2" class="edge">
<title>a.js&#45;&gt;c.js</title>
<path fill="none" stroke="#888888" d="M55.26,-13.83C66.32,-13.45 79.28,-13.06 91,-12.88 115.44,-12.48 121.56,-12.48 146,-12.88 153.88,-13 162.31,-13.22 170.35,-13.46"/>
<polygon fill="#888888" stroke="#888888" points="170.12,-16.95 180.23,-13.78 170.35,-9.96 170.12,-16.95"/>
</g>
<!-- b.js&#45;&gt;c.js -->
<g id="edge3" class="edge">
<title>b.js&#45;&gt;c.js</title>
<path fill="none" stroke="#888888" d="M146.2,-30.27C153.88,-28.38 162.4,-26.27 170.61,-24.24"/>
<polygon fill="#888888" stroke="#888888" points="171.17,-27.71 180.04,-21.91 169.49,-20.91 171.17,-27.71"/>
</g>
</g>
</svg>
"
`)
      /* eslint-enable max-len */
      done()
    })(createSVG(cancel, DEFAULT_GRAPHVIZ_CONFIG, [], modules))
  })(
    checkForBinaries(cancel, '', {
      gvpr: { args: ['-V'] },
      dot: { args: ['-V'] },
    })
  )
})
