// This test automatically generated by doctor-general.
// Sourced from 'knot.js', edits to this file may be erased.

import { strepeat } from '../knot'
test('strepeat', () => {
  expect(strepeat('=', 5)).toEqual('=====')
})
