// This test automatically generated by doctor-general.
// Sourced from 'knot.js', edits to this file may be erased.
import { nthIndex, strepeat, capitalize, slugWord } from '../knot'

test('nthIndex', () => {
  expect(nthIndex('/', -5, 'a/b/c/d/e/f/g/h/i/j')).toEqual('f/g/h/i/j')
  expect(nthIndex('/', 5, 'a/b/c/d/e/f/g/h/i/j')).toEqual('a/b/c/d/e')
})

test('strepeat', () => {
  expect(strepeat('=', 5)).toEqual('=====')
  expect(strepeat('/', -1)).toEqual('')
})

test('capitalize', () => {
  expect(capitalize('nice')).toEqual('Nice')
  expect(capitalize('')).toEqual('')
})

test('slugWord', () => {
  expect(slugWord('CoolFuckingShit')).toEqual('cool-fucking-shit')
  expect(slugWord('hoorayNiceLife')).toEqual('hooray-nice-life')
  expect(slugWord('Do nothingCool ever')).toEqual('do nothing-cool ever')
  expect(
    slugWord('src/components/homepage/AugmentedDetailsDumbComponent')
  ).toEqual('src-components-homepage-augmented-details-dumb-component')
})
