// This test automatically generated by doctor-general.
// Sourced from 'kiddo.js', edits to this file may be erased.
import { signal } from '../kiddo'

import { pipe, map } from 'ramda'
import { readFile } from 'file-system'
import { fork } from 'fluture'
test('signal', done => {
  const cancel = () => {}
  pipe(
    signal(cancel, { text: 'Reading file...', successText: 'Read file!' }),
    map(JSON.parse),
    fork(done)(raw => {
      expect(raw.name).toEqual('kiddo')
      done()
    })
  )(readFile('./package.json'))
})
